# Generated by Django 5.1.6 on 2025-04-01 16:44

import onlinerequest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0005_alter_user_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=onlinerequest.models.profile_image_path),
        ),
    ]
