# Generated by Django 5.1.6 on 2025-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='authorization_letter',
            field=models.TextField(blank=True),
        ),
    ]
