# Generated by Django 5.1.6 on 2025-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0007_user_request_authorization_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='approved_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
