# Generated by Django 5.1.6 on 2025-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0010_databasebackup_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
